"""create

Revision ID: 7b950615b5b8
Revises: 702e78282db3
Create Date: 2025-07-07 16:17:40.910374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b950615b5b8'
down_revision = '702e78282db3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garagem_id', sa.Integer(), nullable=False),
    sa.Column('imagem_filename', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['garagem_id'], ['garagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garagem_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['garagem_id'], ['garagens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('garagem_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentarios')
    op.drop_table('carros')
    op.drop_table('garagens')
    # ### end Alembic commands ###
